version: 2.1

orbs:
    hello: circleci/hello-build@0.0.5
    horie: horie1024/hello-world@dev:first

workflows:
    "Hello Workflow":
        jobs:
          - horie/hello-world:
              your_name: Ryosuke